### ISSUE TITLE
code: 'ERR_STRING_TOO_LONG' with big video files

### ISSUE THREAD

**Issue by MiljenkoLogozar** [muxinc/next-video#107]
Using video files which is 600MB create error:
` ○ Compiling /(rootpage)/page ...
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:646:37)
    at Buffer.toString (node:buffer:865:14)
    at utf8BufferToString (E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:2114)
    at convertArgs (E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:4496)
    at iterateNormalLoaders (E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5761)
    at E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\loader-runner\LoaderRunner.js:1:5426 
    at E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\webpack\bundle5.js:28:399845
    at eval (eval at create (E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:14:1)
    at Array.<anonymous> (E:\dev-OMashram\omashram.com\node_modules\next\dist\build\webpack\plugins\profiling-plugin.js:168:29)
    at runCallbacks (E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\webpack\bundle5.js:1:168123)
    at E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\webpack\bundle5.js:1:170035
    at E:\dev-OMashram\omashram.com\node_modules\next\dist\compiled\webpack\bundle5.js:1:267649
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {      
  code: 'ERR_STRING_TOO_LONG'
}`

Everything works perfectly with small video files (25MB).

**Comment by luwes** [comment]
Thanks for reporting! is it a local video file or a remote file via https:// ?
