### ISSUE TITLE
Unable to upload or access videos on S3

### ISSUE THREAD

**Issue by TheBozzz34** [muxinc/next-video#202]
I am encountering an error running `npx next-video sync` while using s3. 

```
+ Found 1 unprocessed video
- Processing file: Cross.mp4
✗ An unknown error occurred TypeError: Cannot read properties of undefined (reading 'provider')
    at createAsset (file:///E:/ScoreConnect/node_modules/next-video/dist/assets.js:40:27)
    at async newFileProcessor (file:///E:/ScoreConnect/node_modules/next-video/dist/cli/sync.js:68:24)
    at async Promise.all (index 0)
    at async Object.handler (file:///E:/ScoreConnect/node_modules/next-video/dist/cli/sync.js:94:24)
```

I have defined the provider in my `next.config.mjs` like so:

```javascript
import withBundleAnalyzer from "@next/bundle-analyzer";
import withPlugins from "next-compose-plugins";
import { withNextVideo } from "next-video/process";
import { env } from "./env.mjs";

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  reactStrictMode: true,
  experimental: { instrumentationHook: true },
  images: {
    domains: ["avatars.githubusercontent.com", "lh3.googleusercontent.com"],
  },
};

const config = withPlugins([
  [withBundleAnalyzer({ enabled: env.ANALYZE })],
  [withNextVideo(nextConfig, {
    provider: 'amazon-s3',
    providerConfig: {
      'amazon-s3': { 
        endpoint: 'https://s3.us-east-2.amazonaws.com', 
      }
    }
  })]
]);

export default config;
```

And my access keys are in `.env.local`.

I'm not sure why provider is undefined, but I also seem to be unable to access anything at the `/api/video` endpoint, which returns this error.

```
TypeError: Cannot destructure property 'folder' of '(intermediate value)' as it is undefined.
    at getAssetPath (webpack-internal:///(rsc)/./node_modules/next-video/dist/assets.js:31:13)
    at async getAssetConfigPath (webpack-internal:///(rsc)/./node_modules/next-video/dist/assets.js:27:15)
    at async createAsset (webpack-internal:///(rsc)/./node_modules/next-video/dist/assets.js:41:29)
    at async handleRequest (webpack-internal:///(rsc)/./node_modules/next-video/dist/request-handler.js:47:17)
    at async GET (webpack-internal:///(rsc)/./node_modules/next-video/dist/request-handler.js:17:30)
    at async E:\ScoreConnect\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62499
```

**Comment by vkurniavka** [comment]
I had the same error, but before `Cannot destructure property 'folder' `  I have `Failed to load next.config.js or next.config.mjs`

**Comment by luwes** [comment]
shouldn't it be ?

```js
const config = withPlugins([
  [withBundleAnalyzer({ enabled: env.ANALYZE })],
  [withNextVideo({
    provider: 'amazon-s3',
    providerConfig: {
      'amazon-s3': { 
        endpoint: 'https://s3.us-east-2.amazonaws.com/', 
      }
    }
  })]
], nextConfig);
```

check https://github.com/cyrilwanner/next-compose-plugins

**Comment by luwes** [comment]
let me know if it turns out to be something else.
