### ISSUE TITLE
Error [`ERR_REQUIRE_ESM`]: require() of ES Module

### ISSUE THREAD

**Issue by eunchurn** [muxinc/next-video#224]
When I set up the `next.config.js` file in a NextJS project created with Turborepo as follows, 

```js
const { withNextVideo } = require("next-video/process");

/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ["@repo/ui"],
};

module.exports = withNextVideo(nextConfig);
```

I encounter the `ERR_REQUIRE_ESM` error. While the package.json file of the `next-video` sub-package confirms that the `exports` section correctly points to the `./dist/cjs/process.js` file for the `require` module, I don't understand why Turborepo doesn't load this file. Do you know of any Turborepo workarounds or solutions to this issue?

```
ohcamp:dev: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/eunchurn/dev-creative/clev/node_modules/.pnpm/chalk@5.3.0/node_modules/chalk/source/index.js from /Users/eunchurn/dev-creative/clev/node_modules/.pnpm/next-video@0.17.2_@types+react-dom@18.2.24_@types+react@18.2.74_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-video/dist/cjs/providers/mux/provider.js not supported.
ohcamp:dev: Instead change the require of index.js in /Users/eunchurn/dev-creative/clev/node_modules/.pnpm/next-video@0.17.2_@types+react-dom@18.2.24_@types+react@18.2.74_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-video/dist/cjs/providers/mux/provider.js to a dynamic import() which is available in all CommonJS modules.
ohcamp:dev:     at mod.require (/Users/eunchurn/dev-creative/clev/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
ohcamp:dev:     at Object.<anonymous> (/Users/eunchurn/dev-creative/clev/node_modules/.pnpm/next-video@0.17.2_@types+react-dom@18.2.24_@types+react@18.2.74_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-video/dist/cjs/providers/mux/provider.js:38:28) {
ohcamp:dev:   code: 'ERR_REQUIRE_ESM'
ohcamp:dev: }
```

**Comment by luwes** [comment]
I think this might have been a bug, could you try version 
https://github.com/muxinc/next-video/releases/tag/v0.17.3

let us know if the issue persists. thanks!

**Comment by greysteil** [comment]
FWIW, I hit the same issue. Upgrading to v0.17.3 will probably fix it for you, but if it doesn't then switching to a dynamic import worked for me:

<img width="1146" alt="image" src="https://github.com/muxinc/next-video/assets/1144873/1cac3122-15c1-4138-a0ec-0d48ec839efc">

**Comment by dakshshah96** [comment]
@luwes I'm getting this error on the latest version (replacing sensitive data with `xxxxxx`):

```
$ /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/.bin/next-video sync
/Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/strip-ansi/index.js from /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/string-width/index.js not supported.
Instead change the require of /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/strip-ansi/index.js in /Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/xxxxxx/Documents/Projects/xxxxxx/node_modules/string-width/index.js:2:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.11.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by eunchurn** [comment]
@luwes Thank you. it works.

**Comment by luwes** [comment]
@dakshshah96 try removing node_modules and re-installing?

**Comment by dakshshah96** [comment]
@luwes My bad, that fixed it!
