### ISSUE TITLE
Error with ES Module Loading in next-video: ERR_REQUIRE_ESM when requiring chalk in provider.js

### ISSUE THREAD

**Issue by hamzaejaz787** [muxinc/next-video#228]
I followed the docs and used `npx -y next-video init` to add next-video to my project but I'm getting this error when run the app or run the next-video sync command.

The error:
E:\big-o\node_modules\next-video\dist\cjs\providers\mux\provider.js:65
  if (providerMetadata?.playbackId !== playbackId) {
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\big-o\node_modules\next-video\node_modules\chalk\source\index.js from E:\big-o\node_modules\next-video\dist\cjs\providers\mux\provider.js not supported.
Instead change the require of index.js in E:\big-o\node_modules\next-video\dist\cjs\providers\mux\provider.js to a dynamic import() which is available in all CommonJS modules.
    at mod.require (E:\big-o\node_modules\next\dist\server\require-hook.js:65:28)
    at Object.<anonymous> (E:\big-o\node_modules\next-video\dist\cjs\providers\mux\provider.js:43:28) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.11.1

**Comment by hamzaejaz787** [comment]
Idk what I did but its fixed XD
