### ISSUE TITLE
Video config undefined on `npx next-video sync` with Mux

### ISSUE THREAD

**Issue by chricarp** [muxinc/next-video#251]
Hi everyone,
I'm encountering a problem when syncing a video from my `/video` folder to _MUX_.

### The Problem
This is the error when I execute the command: `npx next-video sync`
```bash
+ Found 1 unprocessed video
- Processing file: landing.mp4
✗ An unknown error occurred TypeError: Cannot read properties of undefined (reading 'provider')
    at createAsset (file:///Users/carpi/Desktop/Clan/clanid.it/node_modules/next-video/dist/assets.js:40:27)
    at async newFileProcessor (file:///Users/carpi/Desktop/Clan/clanid.it/node_modules/next-video/dist/cli/sync.js:62:24)
    at async Promise.all (index 0)
    at async Object.handler (file:///Users/carpi/Desktop/Clan/clanid.it/node_modules/next-video/dist/cli/sync.js:88:24)
```
As you can see, the file is found but it fails to read the video configs, as shown into the actual piece of code that fails:
```javascript
async function createAsset(filePath, assetDetails) {
  const videoConfig = await getVideoConfig(); <-- Here the video configs seems to be undefined
  const assetConfigPath = await getAssetConfigPath(filePath);
  let originalFilePath = filePath;
  if (!isRemote(filePath)) {
    originalFilePath = path.relative(cwd(), filePath);
  }
  const newAssetDetails = {
    status: "pending",
    // overwritable
    ...assetDetails,
    originalFilePath,
    provider: videoConfig.provider, <-- here's the line that throws the error
    providerMetadata: {},
    createdAt: Date.now(),
    updatedAt: Date.now()
  };
  [[ other code ]]
}
```

### My setup
NextJS version: **14.0.4**
Next Video version: **1.0.4**
Language: **TypeScript**
`video.d.ts` file: ✅ **Created**
`tsconfig.json` file: ✅ **Modified** with `video.d.ts` included
`next.config.mjs`file: ✅ **Modified**

On the `next.config.mjs`file I need to point out the fact that since my project is using MDX I did have to combine the configurations for Next Video in a way that can work with the already present ones for MDX support.
```javascript
import rehypeShiki from '@leafac/rehype-shiki'
import nextMDX from '@next/mdx'
import { Parser } from 'acorn'
import jsx from 'acorn-jsx'
import escapeStringRegexp from 'escape-string-regexp'
import * as path from 'path'
import { recmaImportImages } from 'recma-import-images'
import remarkGfm from 'remark-gfm'
import { remarkRehypeWrap } from 'remark-rehype-wrap'
import remarkUnwrapImages from 'remark-unwrap-images'
import shiki from 'shiki'
import { unifiedConditional } from 'unified-conditional'
import { withNextVideo } from 'next-video/process'; <<< NEXT VIDEO CHANGES

/** @type {import('next').NextConfig} */
const nextConfig = {
  pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'mdx'],
}

function remarkMDXLayout(source, metaName) {
  let parser = Parser.extend(jsx())
  let parseOptions = { ecmaVersion: 'latest', sourceType: 'module' }

  return (tree) => {
    let imp = `import _Layout from '${source}'`
    let exp = `export default function Layout(props) {
      return <_Layout {...props} ${metaName}={${metaName}} />
    }`

    tree.children.push(
      {
        type: 'mdxjsEsm',
        value: imp,
        data: { estree: parser.parse(imp, parseOptions) },
      },
      {
        type: 'mdxjsEsm',
        value: exp,
        data: { estree: parser.parse(exp, parseOptions) },
      },
    )
  }
}

export default async function config() {
  let highlighter = await shiki.getHighlighter({
    theme: 'css-variables',
  })

  let withMDX = nextMDX({
    extension: /\.mdx$/,
    options: {
      recmaPlugins: [recmaImportImages],
      rehypePlugins: [
        [rehypeShiki, { highlighter }],
        [
          remarkRehypeWrap,
          {
            node: { type: 'mdxJsxFlowElement', name: 'Typography' },
            start: ':root > :not(mdxJsxFlowElement)',
            end: ':root > mdxJsxFlowElement',
          },
        ],
      ],
      remarkPlugins: [
        remarkGfm,
        remarkUnwrapImages,
        [
          unifiedConditional,
          [
            new RegExp(`^${escapeStringRegexp(path.resolve('src/app/blog'))}`),
            [[remarkMDXLayout, '@/app/blog/wrapper', 'article']],
          ],
          [
            new RegExp(`^${escapeStringRegexp(path.resolve('src/app/stories'))}`),
            [[remarkMDXLayout, '@/app/stories/wrapper', 'story']],
          ],
        ],
      ],
    },
  })

  return withMDX(withNextVideo(nextConfig)); <<< NEXT VIDEO CHANGES
}
```

### Conclusion
I'm trying to understand where's my error in the implementation of the library. I was able to get it working (kinda) using a file already present on MUX, but now I want to have also the sync functionality working.

Thanks!

**Comment by luwes** [comment]
be sure to also set the `folder` property in the next-video config!
this is not very well documented I see.
https://github.com/muxinc/next-video/blob/a8db8244a3aa0f7ce220ebf97f0050d3569d4233/src/config.ts#L9-L27


```js
// export default withNextVideo(nextConfig, {
//   folder: 'video'
// });
```

**Comment by chricarp** [comment]
Thank you @luwes very much!

I didn't expect a response and even a new release of the library in just 6 hours, awesome!

**Comment by pedrodalmas** [comment]
Sorry for the delay @luwes 

> is it on Windows or Mac?
- Linux
> what is your module resolution in tsconfig?
- "moduleResolution": "node"

The problem with my next.config.js was in the webpack configuration. After I fixed it, the undefined provider error no longer occurred, but a new one was returned:
```
✗ An unknown error occurred MuxError: The MUX_TOKEN_ID environment variable is missing or empty; either provide it, or instantiate the Mux client with an tokenId option, like new Mux({ tokenId: 'my token id' }).
    at new Mux (.../node_modules/@mux/mux-node/index.mjs:29:19)
    at initMux (.../node_modules/next-video/dist/providers/mux/provider.js:11:17)
    at Module.uploadLocalFile (.../node_modules/next-video/dist/providers/mux/provider.js:99:3)
    at uploadLocalFile (.../node_modules/next-video/dist/handlers/local-upload.js:6:23)
    at callHandler (.../node_modules/next-video/dist/video-handler.js:11:10)
    at newFileProcessor (.../webapp/node_modules/next-video/dist/cli/sync.js:65:16)
    at async Promise.all (index 0)
    at async Object.handler (.../node_modules/next-video/dist/cli/sync.js:88:24)
```

I'm properly setting the `MUX_TOKEN_ID` and `MUX_TOKEN_SECRET` in my .env.local. So I don't know why this error is returned.

**Comment by luwes** [comment]
@pedrodalmas did you find the issue of the missing env vars?
this is very hard to debug without reproducing it so if you could make a minimal reproduction online.
https://github.com/muxinc/next-video/issues/251#issuecomment-2112789735

**Comment by luwes** [comment]
closing due to inactivity
